"""Add is_active to user

Revision ID: f52fc597632e
Revises: 67e97d291284
Create Date: 2025-07-25 14:26:52.583954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f52fc597632e'
down_revision: Union[str, Sequence[str], None] = '67e97d291284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_id'), 'credit_transactions', ['id'], unique=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'credits',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_column('users', 'subscription_expiry')
    op.drop_column('users', 'sync_url')
    op.drop_column('users', 'subscription_type')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'reset_token_expiry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token_expiry', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('subscription_type', sa.VARCHAR(length=8), nullable=True))
    op.add_column('users', sa.Column('sync_url', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('subscription_expiry', sa.DATETIME(), nullable=True))
    op.alter_column('users', 'credits',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'is_active')
    op.drop_index(op.f('ix_credit_transactions_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    # ### end Alembic commands ###
